Update jobs list

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -33,14 +33,14 @@ install:
 - rm -r build
 - rm -r dist
 - rm -r permittivitycalc.egg-info
-script:
-- if  [[ "$COVERAGE" == "true" ]]; then conda install --yes pytest-cov codecov; py.test
-  --cov=./; fi
-after_success:
-- if [[ "$COVERAGE" == "true" ]]; then codecov || echo "codecov upload failed"; fi
-- echo "Build success"
 jobs:
   include:
+    - script:
+      if  [[ "$COVERAGE" == "true" ]]; then conda install --yes pytest-cov codecov; py.test
+      --cov=./; fi
+      after_success:
+        if [[ "$COVERAGE" == "true" ]]; then codecov || echo "codecov upload failed"; fi
+        echo "Build success"
     - stage: deploy
       script: skip
       deploy:
