Revert to old file

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -19,7 +19,6 @@ before_install:
 install:
 - export PATH=$HOME/miniconda/bin:$PATH
 - source activate test-env
-- conda install --yes pytest-cov codecov
 - conda install --file requirements.txt
 - conda list
 - python setup.py install
@@ -33,19 +32,23 @@ jobs:
     sudo: required
     python: 3.6
     script:
-    - py.test --cov=./
+    - if  [[ "$COVERAGE" == "true" ]]; then conda install --yes pytest-cov codecov;
+      py.test --cov=./; fi
     after_success:
-    - codecov || echo "codecov upload failed"
+    - if [[ "$COVERAGE" == "true" ]]; then codecov || echo "codecov upload failed";
+      fi
     - echo "Build success"
-  # - stage: test
-  #   os: osx
-  #   language: generic
-  #   env: TRAVIS_PYTHON_VERSION=3.6
-  #   script:
-  #   - travis_wait python -m pytest --cov=permittivitycalc --cov-report=term
-  #   after_success:
-  #   - codecov || echo "codecov upload failed"
-  #   - echo "Build success"
+  - stage: test
+    os: osx
+    language: generic
+    env: TRAVIS_PYTHON_VERSION=3.6
+    script:
+    - if  [[ "$COVERAGE" == "true" ]]; then conda install --yes pytest-cov codecov;
+      py.test --cov=./; fi
+    after_success:
+    - if [[ "$COVERAGE" == "true" ]]; then codecov || echo "codecov upload failed";
+      fi
+    - echo "Build success"
   - stage: deploy
     python: 3.6
     script: skip
